title: Christopher Tran
logo: /files/chris_head.jpg
description: <br>
  I am a Researcher at Smart Information Flow Technologies (SIFT) working on artificial intelligence and data science. I received my Ph.D. from the University of Illinois Chicago under the advisement of Elena Zheleva.
  <br><br>
  <div class="row">
    <div class="column">
      <a href="https://github.com/chris-tran-16"> <img src="files/github.png" alt="photo" style="width:32px;height:32px;" align="left" hspace="0"></a>
    </div>
    <div class="column">
      <a href="https://twitter.com/chris_tran16"> <img src="files/twitter_black.svg" alt="photo" style="width:32px;height:32px;" align="left" hspace="5"></a>
    </div>
    <div class="column">
      <a href="https://www.linkedin.com/in/christran16/"><img src="files/linkedin.png" alt="photo" style="width:32px;height:32px;" align="left" hspace="0"></a>
    </div>
    <div class="column">
      <a href="mailto:chris.l.tran@gmail.com"><img src="files/email.png" alt="photo" style="width:32px;height:32px;" align="left" hspace="5"></a>
    </div>
  </div>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
#color-scheme: auto-default-dark
